doctrine:
  orm:
    auto_mapping: true
    mappings:
      zentlix_user_admin:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/vendor/zentlix/user-bundle/src/Domain/Admin/Entity'
        prefix: Zentlix\UserBundle\Domain\Admin\Entity
      zentlix_user_group:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/vendor/zentlix/user-bundle/src/Domain/Group/Entity'
        prefix: Zentlix\UserBundle\Domain\Group\Entity
      zentlix_user_journal:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/vendor/zentlix/user-bundle/src/Domain/Journal/Entity'
        prefix: Zentlix\UserBundle\Domain\Journal\Entity
      zentlix_user_mailer:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/vendor/zentlix/user-bundle/src/Domain/Mailer/Entity'
        prefix: Zentlix\UserBundle\Domain\Mailer\Entity
      zentlix_user_user:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/vendor/zentlix/user-bundle/src/Domain/User/Entity'
        prefix: Zentlix\UserBundle\Domain\User\Entity
  dbal:
    types:
      phone: Zentlix\UserBundle\Infrastructure\Share\Doctrine\PhoneType
      email: Zentlix\UserBundle\Infrastructure\Share\Doctrine\EmailType