doctrine:
  orm:
    auto_mapping: true
    mappings:
      Admin:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/vendor/zentlix/user-bundle/src/Domain/Admin/Entity'
        prefix: Zentlix\UserBundle\Domain\Admin\Entity
      Group:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/vendor/zentlix/user-bundle/src/Domain/Group/Entity'
        prefix: Zentlix\UserBundle\Domain\Group\Entity
      Journal:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/vendor/zentlix/user-bundle/src/Domain/Journal/Entity'
        prefix: Zentlix\UserBundle\Domain\Journal\Entity
      Mailer:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/vendor/zentlix/user-bundle/src/Domain/Mailer/Entity'
        prefix: Zentlix\UserBundle\Domain\Mailer\Entity
      User:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/vendor/zentlix/user-bundle/src/Domain/User/Entity'
        prefix: Zentlix\UserBundle\Domain\User\Entity
  dbal:
    types:
      phone: Zentlix\UserBundle\Infrastructure\Share\Doctrine\PhoneType
      email: Zentlix\UserBundle\Infrastructure\Share\Doctrine\EmailType